name: flutter_webrtc_demo
description: A new Flutter application.
version: 1.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_webrtc: ^0.6.0
  shared_preferences: ^2.0.0
  http: ^0.13.0
  path_provider: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
